### RS485
uart:
  id: modbus_serial
  rx_pin: ${uart_rx_pin}
  tx_pin: ${uart_tx_pin}
  baud_rate: 4800
  stop_bits: 1

modbus:
  id: modbus1
  uart_id: modbus_serial
 
modbus_controller:
  - id: con_modbus_name
    update_interval: 20s
    address: 0x1
    command_throttle: 100ms
    setup_priority: -10
    

number:
# How many gallons of plant root space? Only gallons because theyre more common pot sizes than liters
  - platform: template
    id: media_volume
    name: "Media Volume"
    icon: "mdi:water-percent"
    min_value: 0
    max_value: 20
    initial_value: 2
    step: 1
    restore_value: true
    optimistic: True
    mode: box
    entity_category: config
    unit_of_measurement: "Gallons"
# Plant count so we can figure out how much water we are using 
  - platform: template
    id: plant_count
    name: "Plant Count"
    icon: "mdi:sprout"
    min_value: 1
    max_value: 36
    initial_value: 9
    step: 1
    restore_value: true
    optimistic: True
    mode: box
    entity_category: config
    unit_of_measurement: "plants"
    
# This is the total drip rate each plant is getting per minute.
# If you have 1 liter per minute drippers, and you use 2 drippers per plant, this should be 2000
  - platform: template
    id: drip_rate
    name: "Drip Rate"
    icon: "mdi:water-percent"
    min_value: 01
    max_value: 100000
    initial_value: 1250
    step: 1
    restore_value: true
    optimistic: True
    mode: box
    entity_category: config
    unit_of_measurement: ml/minute   
# The P0 dryback target is how much VWC should drop after lights on before irrigations start 
  - platform: template
    id: p0_dryback_target
    name: "P0 Dryback Target"
    icon: "mdi:water-percent"
    min_value: 0
    max_value: 15
    initial_value: 3
    step: 1
    restore_value: true
    optimistic: True
    mode: box
    entity_category: config
    unit_of_measurement: "%"
# How Often P1 waters
  - platform: template
    id: p1_frequency
    name: "P1 Frequency"
    icon: "mdi:water-percent"
    min_value: 0
    max_value: 60
    initial_value: 15
    step: 1
    restore_value: true
    optimistic: True
    mode: box
    entity_category: config 
    unit_of_measurement: minutes
# VWC % Shot size target
  - platform: template
    id: p1_shot_size
    name: "P1 Shot %"
    icon: "mdi:water-percent"
    min_value: 0
    max_value: 25
    initial_value: 5
    step: 0.1
    restore_value: true
    optimistic: True
    mode: box
    entity_category: config
    unit_of_measurement: "%"
# This is the maximum amount of shots P1 should try before switching to P2
  - platform: template
    id: p1_target_shots
    name: "P1 Target Shots"
    icon: "mdi:water-percent"
    min_value: 0
    max_value: 16
    initial_value: 5
    step: 1
    restore_value: true
    optimistic: True
    mode: box
    entity_category: config
# An internal counter to keep track of how many shots we have done
  - platform: template
    id: p1_shot_count
    name: "P1 Shots"
    internal: true
    min_value: 0
    max_value: 33
    initial_value: 0
    step: 1
    restore_value: true
    optimistic: True
    on_value:  # each shot, we update the text sensor to show how many shots
      - text_sensor.template.publish:
          id: p1_shot_count_display
          state: !lambda "return {to_string(round(id(p1_shot_count).state))};"
# An EC target to use for ending P1, if its not low enough keep going in vegetative
  - platform: template
    id: p2_ec_target
    name: "P2 EC Target"
    icon: "mdi:water-percent"
    min_value: 0
    max_value: 100
    initial_value: 3.0
    step: 0.1
    restore_value: true
    optimistic: True
    mode: box
    entity_category: config
    unit_of_measurement: "EC"

  - platform: template
    id: p2_dryback_target
    name: "P2 Dryback Target"
    icon: "mdi:water-percent"
    min_value: 0
    max_value: 100
    initial_value: 0
    step: 1
    restore_value: true
    optimistic: True
    mode: box
    entity_category: config
    unit_of_measurement: "%"
  - platform: template
    id: p2_shot_size
    name: "P2 Shot Size"
    icon: "mdi:water-percent"
    min_value: 0
    max_value: 100
    initial_value: 0
    step: 0.1
    restore_value: true
    optimistic: True
    mode: box
    entity_category: config
    unit_of_measurement: "%"
    
  - platform: template
    id: p3_dryback_target
    name: "P3 Dryback Target"
    icon: "mdi:water-percent"
    min_value: 0
    max_value: 100
    initial_value: 0
    step: 1
    restore_value: true
    optimistic: True
    mode: box
    entity_category: config
    unit_of_measurement: "%"
# This is the low VWC limit our plants should ever get, below this is wilt territory
  - platform: template
    id: p3_vwc_low_limit
    name: "P3 VWC Low Limit"
    icon: "mdi:alert-octagon"
    min_value: 0
    max_value: 100
    initial_value: 20
    step: 1
    restore_value: true
    optimistic: True
    mode: box
    entity_category: config   
    unit_of_measurement: "%"
 
 # lets count the daily irrigation events.
  - platform: template
    id: daily_irrigation_events
    name: "Daily Irrigation Events"
    internal: true
    min_value: 0
    max_value: 50
    initial_value: 0
    step: 1
    restore_value: true
    optimistic: True
    on_value:  # each shot, we update the text sensor to show how many shots
      - text_sensor.template.publish:
          id: daily_shot_count_display
          state: !lambda "return {to_string(round(id(daily_irrigation_events).state))};"
